application: pocketbudda
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style
- url: /web
  static_dir: web
- url: /mweb
  static_dir: mweb
- url: /favicon.ico
  static_files: web/favicon.ico
  upload: web/favicon.ico
- url: /xd_receiver.htm
  static_files: xd_receiver.htm
  upload: xd_receiver.htm
- url: .*
  script: main.py
